# .readthedocs.yaml
# Read the Docs configuration file
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install additional dependencies
      - pip install sphinx-rtd-theme
      - pip install sphinx-autodoc-typehints
      - pip install nbsphinx
      - pip install ipykernel
      - pip install pyabf
      - pip install pandas
      - pip install numpy
      - pip install scipy
      - pip install tqdm
  apt_packages:
    - pandoc

# Build documentation in the docs/source directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally declare the Python requirements required to build docs
python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

# Generate PDF & ePub
formats:
  - pdf
  - epub